spring:
  server:
    port: 8080
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: test
    url: jdbc:postgresql://77.73.71.129:5433/testdb?currentSchema=testuser
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

